<a href="https://colab.research.google.com/github/MrP-cpu/AI_Lab/blob/master/lab_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment_1

##Ex1

In [ ]:
#ex1
def relu(x):
  if x >= 0:
    print(x);
  else :
    print("o")
    return

#calling the function
relu(-3)

o




##Ex2



In [ ]:
#ex2
#euclidean norm
from numpy.linalg import norm
def euclidean_norm(vector):
#square root of the sum of the squares of vector's components
  print("this is the vector:-", vector)
  norm_vector=norm(vector)
  print("this is the norm of vector:-" ,norm_vector)
  return

import numpy as np
my_vector = [0.5, -1.2, 3.3, 4.5]

euclidean_norm(my_vector)

this is the vector:- [0.5, -1.2, 3.3, 4.5]
this is the norm of vector:- 5.729746940310715


##Ex3


In [ ]:
#ex3

def vector_maximum(vector):
  #the function of the vector
  largest = vector[0]

  for i in vector:
    if i>largest:
      largest=i
  print("this is the largest number:-",largest)
  return

vector=[3 , 4 , 6  , 6 , 8 ]
vector_maximum(vector)

this is the largest number:- 8




#BONUS EXCERCISE




##LAB ASSIGNMENT_1
```
`# This is formatted as code`
```



In [ ]:
#Q1->Given two lists—one containing keys and the other containing values. Create a dictionary by pairing corresponding elements from both lists.
  # Define the lists
keys = ["name", "age", "country"]
values = ["Alice", 30, "USA"]

# Create the dictionary using zip() and dict()
dictionary = dict(zip(keys, values))

# Print the resulting dictionary
print(dictionary)

{'name': 'Alice', 'age': 30, 'country': 'USA'}


In [ ]:
##Q2->Write a program that compares two numbers and prints whether they are equal, not equal, greater than, or less than each other.

# Function to compare two numbers
def compareNumbers(a, b):
    if a == b:
        print(f"{a} is equal to {b}")
    elif a > b:
        print(f"{a} is greater than {b}")
    else:
        print(f"{a} is less than {b}")

# User input
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

# Compare the numbers
compareNumbers(num1, num2)

Enter the first number: 24
Enter the second number: 24
24.0 is equal to 24.0


In [ ]:
##Q3->Create a list of length 10 of your choice containing multiple types of data. Using for loop print the element and its data type.

my_list = [42, "hello", 3.14, True, None, [1, 2, 3], {'key': 'value'}, (7, 8), {9, 10}, b"bytes"]

for element in my_list:
    print(f"Element: {element}, Type: {type(element)}")

Element: 42, Type: <class 'int'>
Element: hello, Type: <class 'str'>
Element: 3.14, Type: <class 'float'>
Element: True, Type: <class 'bool'>
Element: None, Type: <class 'NoneType'>
Element: [1, 2, 3], Type: <class 'list'>
Element: {'key': 'value'}, Type: <class 'dict'>
Element: (7, 8), Type: <class 'tuple'>
Element: {9, 10}, Type: <class 'set'>
Element: b'bytes', Type: <class 'bytes'>


In [ ]:
##Q4->Using a while loop, verify if the number A is purely divisible by number B and if so then how many times it can be divisible.

def countDivisibility(A, B):
    count = 0
    while A % B == 0:
        A = A // B
        count += 1
    return count

# User input
A = int(input("Enter the value for A: "))
B = int(input("Enter the value for B: "))

if B == 0:
    print("Division by zero is not allowed.")
else:
    count = countDivisibility(A, B)
    if count > 0:
        print(f"{A * (B ** count)} is divisible by {B} {count} times.")
    else:
        print(f"{A} is not divisible by {B}.")

Enter the value for A: 24
Enter the value for B: 35
24 is not divisible by 35.


In [ ]:
##Q5->Create a list containing 25 integer type data. Using for loop and if-else condition print if the element is divisible by 3 or not.
# List containing 25 integer type data
my_list = [5, 9, 15, 20, 33, 42, 17, 50, 27, 14, 12, 24, 55, 61, 63, 75, 81, 90, 99, 100, 111, 120, 125, 150, 180]

# Using a for loop to check if each element is divisible by 3
for number in my_list:
    if number % 3 == 0:
        print(f"{number} is divisible by 3.")
    else:
        print(f"{number} is not divisible by 3.")

5 is not divisible by 3.
9 is divisible by 3.
15 is divisible by 3.
20 is not divisible by 3.
33 is divisible by 3.
42 is divisible by 3.
17 is not divisible by 3.
50 is not divisible by 3.
27 is divisible by 3.
14 is not divisible by 3.
12 is divisible by 3.
24 is divisible by 3.
55 is not divisible by 3.
61 is not divisible by 3.
63 is divisible by 3.
75 is divisible by 3.
81 is divisible by 3.
90 is divisible by 3.
99 is divisible by 3.
100 is not divisible by 3.
111 is divisible by 3.
120 is divisible by 3.
125 is not divisible by 3.
150 is divisible by 3.
180 is divisible by 3.


In [ ]:
##Q6->Given a list my list = [1, 2, 3, 4, 5], write the code to slice the list and obtain the sub-list [2, 3].
# Given list
my_list = [1, 2, 3, 4, 5]

sub_list = my_list[1:3]

# Output the sub-list
print(sub_list)

[2, 3]


In [ ]:
##Q7->iven the string "Hello, World!", extract the sub-string "World".
# Given string
my_string = "Hello, World!"

# Extracting the sub-string "World"
sub_string = my_string[7:12]

# Output the sub-string
print(sub_string)

World


In [ ]:
##Q8->Calculatethemultiplicationandsumoftwonumbers:Giventwointeger numbers, return their product only if the product is equal to or lower than 1000. Otherwise, return their sum
# Function to calculate the multiplication and sum of two numbers
def calculate(a, b):
    product = a * b
    if product <= 1000:
        return product
    else:
        return a + b

# User input
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Calculate and print the result
result = calculate(num1, num2)
print("The result is:", result)

Enter the first number: 100
Enter the second number: 20
The result is: 120


In [ ]:
##Q9->Write a program to iterate through the first 10 numbers, and in each Print characters from a string that are present at an even index number. Accept a string from the user and display characters that are present at an even index number.
# Function to print characters at even index positions
def print_even_index_chars(input_string):
    print("Characters at even index positions are:")
    even_chars = [input_string[i] for i in range(0, len(input_string), 2)]
    print(''.join(even_chars))

# Accept a string from the user
user_string = input("Enter a string: ")

# Iterate through the first 10 numbers
for num in range(1, 11):
    print(f"\nIteration {num}:")
    print_even_index_chars(user_string)

Enter a string: there a ghost

Iteration 1:
Characters at even index positions are:
teeagot

Iteration 2:
Characters at even index positions are:
teeagot

Iteration 3:
Characters at even index positions are:
teeagot

Iteration 4:
Characters at even index positions are:
teeagot

Iteration 5:
Characters at even index positions are:
teeagot

Iteration 6:
Characters at even index positions are:
teeagot

Iteration 7:
Characters at even index positions are:
teeagot

Iteration 8:
Characters at even index positions are:
teeagot

Iteration 9:
Characters at even index positions are:
teeagot

Iteration 10:
Characters at even index positions are:
teeagot


In [ ]:
## 10. Write a program to iterate through the list and find the even number & its count.
numbers = [1, 2, 4, 5, 6, 8]
count = 0

for num in numbers:
    if num % 2 == 0:
        count += 1
        print(f"Even number: {num}")

# Print the count of even numbers
print(f"Total count of even numbers: {count}")

print("The list is", numbers)

Even number: 2
Even number: 4
Even number: 6
Even number: 8
Total count of even numbers: 4
The list is [1, 2, 4, 5, 6, 8]


In [ ]:
##Q11. Write a program to find the minimum value of a list of numbers 5,3,8,-1,2.2,0 (Don’t use built in function).
numbers = [5, 3, 8, -1, 2.2, 0]
minimum = numbers[0]

for num in numbers:
    if num < minimum:
        minimum = num

print("The minimum value is:", minimum)



The minimum value is: -1


In [ ]:
##Q12. Write a programme to iterate over a list of strings and check whether a particular word is in or not?

string_list = ["apple", "banana split", "cherry tart", "apple crumble"]
check = "apple"

# Flag to indicate if the word was found
found = False

for string in string_list:
    if check in string:
        print(f"The word 'check' is found in: '{string}'")
        found = True
if not found:
    print(f"The word 'check' was not found in any string.")



The word 'check' is found in: 'apple'
The word 'check' is found in: 'apple crumble'


In [ ]:
##Q13->Write a programme that uses a while loop to test whether user input a password "Secret" other wise print " Your password is incorrect".

while True:
    password =input('Enter the password :')
    if password == 'Secret':
        print('your password is correct')
        break
    else:
      print('password is wrong')
      break

Enter the password :new
password is wrong


In [ ]:
##Q14-> Write a program to show
##(a) Exit a loop using break
##(b) Exit a loop using Continue

##(a)
while True:
    password =input('Enter the password :')
    if password == 'Secret':
        print('your password is correct')
        break
    else:
      print('password is wrong')
      break


##(b)
for num in range(1, 11):
    if num % 2 == 0:
        continue
    print(num)

Enter the password :new
password is wrong
1
3
5
7
9


In [ ]:
##Q15->Write a programme that asks the user for number (int) . It computes the average of a number & allows the user to enter-1 to quit

total = 0
count = 0

while True:
    number = int(input("Enter a number (or enter -1 to quit): "))

    if number == -1:
        break

    total += number
    count += 1

if count > 0:
    average = total / count
    print(f"The average of the entered numbers is: {average}")
else:
    print("No numbers were entered.")



Enter a number (or enter -1 to quit): 4
Enter a number (or enter -1 to quit): 5
Enter a number (or enter -1 to quit): -1
The average of the entered numbers is: 4.5


In [ ]:
 ##Q16. Write a programme with function get_factor that takes an integer as a parameter and return a list of factors of that number.

 def get_factors(number):
    factors = []
    for i in range(1, number + 1):
        if number % i == 0:
            factors.append(i)
    return factors

num = 12
factors_of_num = get_factors(num)
print(f"The factors of {num} are: {factors_of_num}")

The factors of 12 are: [1, 2, 3, 4, 6, 12]


In [ ]:
##Q17. Write a program with a function unique_list that takes a list of numbers as a parameter and return a new list with the unique list.

def unique_list(numbers):
    unique_numbers = []
    for num in numbers:
        if num not in unique_numbers:
            unique_numbers.append(num)
    return unique_numbers

numbers = [1, 2, 2, 3, 4, 4, 5, 6, 6]
unique_numbers = unique_list(numbers)
print(f"The unique numbers in the list are: {unique_numbers}")

The unique numbers in the list are: [1, 2, 3, 4, 5, 6]


In [ ]:
#BONUS EXCERCISE
#bubble sort

def bubble_sort(my_list)


In [ ]:
##Q18. Write a programme to create a dictionary of three students with their details like name,grades & attendance of 5 subjects in list. Then create another dictionary which is having roll no as keys and name of the students as values. Write another programme to get average of all the marks.

# Dictionary of three students with their details
students_details = {
    1: {"name": "Raju", "grades": [85, 90, 78, 92, 88], "attendance": [True, True, True, False, True]},
    2: {"name": "Ramu", "grades": [75, 80, 68, 82, 78], "attendance": [True, True, False, True, True]},
    3: {"name": "Ramesh", "grades": [95, 92, 88, 96, 94], "attendance": [True, True, True, True, True]}
}

# Dictionary with roll numbers as keys and student names as values
roll_no_to_name = {roll_no: details["name"] for roll_no, details in students_details.items()}

print("Roll Number to Name Mapping:")
print(roll_no_to_name)

# average marks
def calculate_average_marks(students):
    average_marks = {}
    for roll_no, details in students.items():
        average_marks[roll_no] = sum(details["grades"]) / len(details["grades"])
    return average_marks

average_marks = calculate_average_marks(students_details)

print("\nAverage Marks of Each Student:")
for roll_no, avg in average_marks.items():
    print(f"Roll No {roll_no} ({roll_no_to_name[roll_no]}): {avg}")



Roll Number to Name Mapping:
{1: 'Raju', 2: 'Ramu', 3: 'Ramesh'}

Average Marks of Each Student:
Roll No 1 (Raju): 86.6
Roll No 2 (Ramu): 76.6
Roll No 3 (Ramesh): 93.0


## Assignment 2
Searching and sorting algorithm using python


In [ ]:
#Linear Searching
# Linear Search
arr = []
for i in range(5):
    m = int(input(f"Enter {i+1} element: "))
    arr.append(m)

print("Array is: ", arr)
search_element = int(input("Enter searching element: "))
c = 0

for n in arr:
    if n == search_element:
        c += 1
        break

if c > 0:
    print("Searching element present")
else:
    print("Searching element not present")

Enter 1 element: 1
Enter 2 element: 2
Enter 3 element: 4
Enter 4 element: 5
Enter 5 element: 7
Array is:  [1, 2, 4, 5, 7]
Enter searching element: 7
Searching element present


In [ ]:
# Binary Search
arr2 = []
for i in range(10):
    a = int(input(f"Enter {i+1} element: "))
    arr2.append(a)

arr2.sort()  # Make sure the array is sorted for binary search
print("Array is: ", arr2)

se = int(input("Enter searching element: "))
s = 0
e = len(arr2) - 1
c = 0

while s <= e:
    mid = (s + e) // 2
    if se > arr2[mid]:
        s = mid + 1
    elif se == arr2[mid]:
        c += 1
        break
    else:
        e = mid - 1

if c > 0:
    print("Searching element present")
else:
    print("Searching element not present")
4

Enter 1 element: 1
Enter 2 element: 2
Enter 3 element: 3
Enter 4 element: 4
Enter 5 element: 5
Enter 6 element: 6
Enter 7 element: 7
Enter 8 element: 8
Enter 9 element: 9
Enter 10 element: 10
Array is:  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Enter searching element: 6
Searching element present


4

In [ ]:
# Bubble Sort
arr1 = []
for i in range(7):
    n = int(input(f"Enter {i+1} element: "))
    arr1.append(n)

print("Array is: ", arr1)

for i in range(len(arr1)):
    for j in range(0, len(arr1) - i - 1):
        if arr1[j] > arr1[j+1]:
            arr1[j], arr1[j+1] = arr1[j+1], arr1[j]

print("Sorted Array is: ", arr1)

Enter 1 element: 2
Enter 2 element: 1
Enter 3 element: 4
Enter 4 element: 6
Enter 5 element: 3
Enter 6 element: 7
Enter 7 element: 3
Array is:  [2, 1, 4, 6, 3, 7, 3]
Sorted Array is:  [1, 2, 3, 3, 4, 6, 7]


In [ ]:
# Selection Sort
def selection_sort(arr):
    for i in range(len(arr)):
        minimum = i
        for j in range(i + 1, len(arr)):
            if arr[j] < arr[minimum]:
                minimum = j
        arr[i], arr[minimum] = arr[minimum], arr[i]
    return arr

arr = []
for i in range(5):
    m = int(input(f"Enter {i+1} element: "))
    arr.append(m)

print("Array is: ", arr)
sorted_arr = selection_sort(arr)
print(f"Sorted array is: {sorted_arr}")



Enter 1 element: 2
Enter 2 element: 4
Enter 3 element: 1
Enter 4 element: 5
Enter 5 element: 3
Array is:  [2, 4, 1, 5, 3]
Sorted array is: [1, 2, 3, 4, 5]


In [ ]:
# Insertion Sort
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

arr = []
for i in range(5):
    m = int(input(f"Enter {i+1} element: "))
    arr.append(m)

print("Array is: ", arr)
sorted_arr = insertion_sort(arr)
print(f"Sorted array is: {sorted_arr}")


Enter 1 element: 1
Enter 2 element: 2
Enter 3 element: 3
Enter 4 element: 4
Enter 5 element: 6
Array is:  [1, 2, 3, 4, 6]
Sorted array is: [1, 2, 3, 4, 6]


In [ ]:
# Merge Sort
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2
        lh = arr[:mid]
        rh = arr[mid:]

        merge_sort(lh)
        merge_sort(rh)

        i = j = k = 0
        while i < len(lh) and j < len(rh):
            if lh[i] < rh[j]:
                arr[k] = lh[i]
                i += 1
            else:
                arr[k] = rh[j]
                j += 1
            k += 1

        while i < len(lh):
            arr[k] = lh[i]
            i += 1
            k += 1

        while j < len(rh):
            arr[k] = rh[j]
            j += 1
            k += 1

    return arr

arr = []
for i in range(5):
    m = int(input(f"Enter {i+1} element: "))
    arr.append(m)

print("Array is: ", arr)
sorted_arr = merge_sort(arr)
print(f"Sorted array is: {sorted_arr}")


Enter 1 element: 1
Enter 2 element: 3
Enter 3 element: 4
Enter 4 element: 6
Enter 5 element: 7
Array is:  [1, 3, 4, 6, 7]
Sorted array is: [1, 3, 4, 6, 7]


In [ ]:
# Quick Sort
def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quick_sort(arr, low, high):
    if low < high:
        pi = partition(arr, low, high)
        quick_sort(arr, low, pi - 1)
        quick_sort(arr, pi + 1, high)

arr = []
for i in range(5):
    m = int(input(f"Enter {i+1} element: "))
    arr.append(m)

print("Array is: ", arr)
n = len(arr)
quick_sort(arr, 0, n - 1)
print(f"Sorted array is: {arr}")


Enter 1 element: 1
Enter 2 element: 2
Enter 3 element: 6
Enter 4 element: 2
Enter 5 element: 3
Array is:  [1, 2, 6, 2, 3]
Sorted array is: [1, 2, 2, 3, 6]


# Assignment3

##Q1

In [ ]:
##Write a python program to implement different arithmetic operation such as
#addition,subtraction,multiplication,division and exponent
def add(a,b):
    sum=a+b
    return sum

def sub(a,b):
    sub=a-b
    return sub

def mul(a,b):
    mul=a*b
    return mul

def div(a,b):
    div=a/b
    return div

def exp(a,b):
    exp=a^b
    return exp
print("the sum is: ",add(4,5))
print("the difference :",sub(4,5))
print("the multiplication is:",mul(4,5))


the sum is:  9
the difference : -1
the multiplication is: 20


##Q2

In [ ]:
##Write a python program to implement the Boolean logic function( AND,OR,NOT etc)
# Boolean logic functions

def AND(a, b):
    return a and b

def OR(a, b):
    return a or b

def NOT(a):
    return not a

def XOR(a, b):
    return a ^ b  # XOR operator in Python

def NAND(a, b):
    return not (a and b)

# Test cases
a = True
b = False

# Display results
print(f"AND({a}, {b}) = {AND(a, b)}")
print(f"OR({a}, {b}) = {OR(a, b)}")
print(f"NOT({a}) = {NOT(a)}")
print(f"XOR({a}, {b}) = {XOR(a, b)}")
print(f"NAND({a}, {b}) = {NAND(a, b)}")

AND(True, False) = False
OR(True, False) = True
NOT(True) = False
XOR(True, False) = True
NAND(True, False) = True


## Q3

In [ ]:
##3. Write a python code to perform certain operation on the string such as print a string,
## concatenation of two string, Capitalize a string, convert a string to uppercase,
##accessing substring from a given string

# Function to perform various string operations
def string_operations():
    # 1. Print a string
    my_string = "Hello, World!"
    print("Original String:", my_string)

    # 2. Concatenation of two strings
    string1 = "Hello"
    string2 = "Python"
    concatenated_string = string1 + " " + string2
    print("Concatenated String:", concatenated_string)

    # 3. Capitalize a string
    capitalized_string = my_string.capitalize()  # Capitalizes only the first character
    print("Capitalized String:", capitalized_string)

    # 4. Convert a string to uppercase
    uppercase_string = my_string.upper()
    print("Uppercase String:", uppercase_string)

    # 5. Access a substring from a given string
    substring = my_string[7:12]  # Accessing characters from index 7 to 11
    print("Substring from the string:", substring)

# Call the function
string_operations()


Original String: Hello, World!
Concatenated String: Hello Python
Capitalized String: Hello, world!
Uppercase String: HELLO, WORLD!
Substring from the string: World


##Q4

In [ ]:
##Write a python code to create a list with different data types, access elements of lists, slicing,
## append ,remove elements from the list and find length of the list.

# Create a list with different data types
my_list = [25, "Hello", 3.14, True, [1, 2, 3]]

# Access elements from the list
print("Accessing individual elements:")
print("Element at index 0:", my_list[0])  # First element
print("Element at index 1:", my_list[1])  # Second element
print("Element at index 4:", my_list[4])  # Fifth element (which is a list itself)

# Slicing the list
print("\nSlicing the list:")
print("First three elements:", my_list[:3])  # Slice first 3 elements
print("Last two elements:", my_list[-2:])  # Slice last 2 elements

# Append a new element to the list
my_list.append("New Element")
print("\nList after appending a new element:")
print(my_list)

# Remove an element from the list
my_list.remove(3.14)
print("\nList after removing the element '3.14':")
print(my_list)

# Find the length of the list
list_length = len(my_list)
print("\nLength of the list:", list_length)

Accessing individual elements:
Element at index 0: 25
Element at index 1: Hello
Element at index 4: [1, 2, 3]

Slicing the list:
First three elements: [25, 'Hello', 3.14]
Last two elements: [True, [1, 2, 3]]

List after appending a new element:
[25, 'Hello', 3.14, True, [1, 2, 3], 'New Element']

List after removing the element '3.14':
[25, 'Hello', True, [1, 2, 3], 'New Element']

Length of the list: 5



##Q5

In [ ]:
##Write a python code to find sum of the array and the largest number in the the array
# Function to find the sum of the array
def array_sum(arr):
    return sum(arr)

# Function to find the largest number in the array
def largest_number(arr):
    return max(arr)

# Main function
def main():
    # Input: array from the user
    arr = list(map(int, input("Enter the elements of the array separated by space: ").split()))

    # Find and print the sum of the array
    total_sum = array_sum(arr)
    print("Sum of the array:", total_sum)

    # Find and print the largest number in the array
    largest = largest_number(arr)
    print("Largest number in the array:", largest)

# Call the main function
main()


Enter the elements of the array separated by space: 2 3 4 5 6 
Sum of the array: 20
Largest number in the array: 6


##Q6


In [ ]:
import numpy as np

# Define two matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Add, subtract, multiply, and transpose each result in a single line
add_result = np.transpose(A + B)
subtract_result = np.transpose(A - B)
multiply_result = np.transpose(A * B)  # Element-wise multiplication

# Print the results
print("Transpose of the Addition of matrices:\n", add_result)
print("Transpose of the Subtraction of matrices:\n", subtract_result)
print("Transpose of the Element-wise Multiplication of matrices:\n", multiply_result)

Transpose of the Addition of matrices:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Transpose of the Subtraction of matrices:
 [[-8 -2  4]
 [-6  0  6]
 [-4  2  8]]
Transpose of the Element-wise Multiplication of matrices:
 [[ 9 24 21]
 [16 25 16]
 [21 24  9]]


##Q7

In [ ]:
# Creating a dictionary with different data types as values
my_dict = {
    "name": "Alice",          # String
    "age": 25,                # Integer
    "is_student": True,       # Boolean
    "marks": [88, 92, 79],    # List
    "address": {"city": "NY", "zip": 10001}  # Nested dictionary
}

# Accessing elements from the dictionary
print("Name:", my_dict["name"])  # Accessing by key 'name'
print("Age:", my_dict["age"])    # Accessing by key 'age'
print("Is Student:", my_dict["is_student"])  # Accessing by key 'is_student'
print("Marks:", my_dict["marks"])  # Accessing the list of marks
print("City:", my_dict["address"]["city"])  # Accessing a nested dictionary

# Adding elements to the dictionary
my_dict["email"] = "alice@example.com"  # Adding a new key-value pair
print("\nDictionary after adding email:", my_dict)

# Removing elements from the dictionary
removed_element = my_dict.pop("is_student")  # Removing key 'is_student'
print("\nRemoved element (is_student):", removed_element)
print("Dictionary after removing 'is_student':", my_dict)

# Removing another element using 'del'
del my_dict["age"]
print("\nDictionary after removing 'age':", my_dict)

Name: Alice
Age: 25
Is Student: True
Marks: [88, 92, 79]
City: NY

Dictionary after adding email: {'name': 'Alice', 'age': 25, 'is_student': True, 'marks': [88, 92, 79], 'address': {'city': 'NY', 'zip': 10001}, 'email': 'alice@example.com'}

Removed element (is_student): True
Dictionary after removing 'is_student': {'name': 'Alice', 'age': 25, 'marks': [88, 92, 79], 'address': {'city': 'NY', 'zip': 10001}, 'email': 'alice@example.com'}

Dictionary after removing 'age': {'name': 'Alice', 'marks': [88, 92, 79], 'address': {'city': 'NY', 'zip': 10001}, 'email': 'alice@example.com'}


##Q8


In [ ]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

# Print prime numbers less than 20
print("Prime numbers less than 20:")
for number in range(20):
    if is_prime(number):
        print(number, end=" ")

Prime numbers less than 20:
2 3 5 7 11 13 17 19 

##Q9

In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

# Example usage
num = 5
print(f"Factorial of {num} is {factorial(num)}")

Factorial of 5 is 120


##Q10

In [ ]:
# Creating a tuple
my_tuple = (3, 1, 9, 7, 4, 6, 8)

# Find maximum and minimum elements in the tuple
max_element = max(my_tuple)
min_element = min(my_tuple)

# Find the size of the tuple
tuple_size = len(my_tuple)

# Display the results
print(f"Tuple: {my_tuple}")
print(f"Maximum element in the tuple: {max_element}")
print(f"Minimum element in the tuple: {min_element}")
print(f"Size of the tuple: {tuple_size}")

Tuple: (3, 1, 9, 7, 4, 6, 8)
Maximum element in the tuple: 9
Minimum element in the tuple: 1
Size of the tuple: 7


##Q11

In [ ]:
from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)

    while queue:
        vertex = queue.popleft()
        print(vertex, end=" ")

        for neighbor in graph[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

# Example graph as adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# Perform BFS
print("Breadth-First Search starting from vertex A:")
bfs(graph, 'A')

Breadth-First Search starting from vertex A:
A B C D E F 

##Q12

In [ ]:
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    visited.add(start)

    print(start, end=" ")

    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs(graph, neighbor, visited)

# Example graph as adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': [],
    'E': ['F'],
    'F': []
}

# Perform DFS
print("Depth-First Search starting from vertex A:")
dfs(graph, 'A')

Depth-First Search starting from vertex A:
A B D E F C 

##Assignment 4

In [ ]:
def is_safe(board, row, col, N):
    # Check this row on the left side
    for i in range(col):
        if board[row][i] == 1:
            return False

    # Check the upper diagonal on the left side
    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    # Check the lower diagonal on the left side
    for i, j in zip(range(row, N, 1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    return True


def solve_n_queens_util(board, col, N):
    # If all queens are placed
    if col >= N:
        return True

    # Try placing queens in all rows one by one
    for i in range(N):
        if is_safe(board, i, col, N):
            # Place this queen on board[i][col]
            board[i][col] = 1

            # Recursively place rest of the queens
            if solve_n_queens_util(board, col + 1, N):
                return True

            # If placing queen in board[i][col] doesn't lead to a solution, backtrack
            board[i][col] = 0  # Backtrack

    # If queen cannot be placed in any row in this column col, return False
    return False


def solve_n_queens(N):
    board = [[0] * N for _ in range(N)]  # Initialize N x N board

    if not solve_n_queens_util(board, 0, N):
        print("Solution does not exist")
        return False

    print_board(board)
    return True


def print_board(board):
    for row in board:
        print(" ".join('Q' if x == 1 else '.' for x in row))
    print()


# Test the solution
N = 8  # You can change N to solve for different board sizes
solve_n_queens(N)


Q . . . . . . .
. . . . . . Q .
. . . . Q . . .
. . . . . . . Q
. Q . . . . . .
. . . Q . . . .
. . . . . Q . .
. . Q . . . . .



True

Ques2

In [ ]:
import heapq

# A* Problem
class Node:
    def __init__(self, position, parent=None):
        self.position = position
        self.parent = parent
        self.g = 0  # Cost from start to current node
        self.h = 0  # Heuristic - estimated cost to goal
        self.f = 0  # Total cost

    def __lt__(self, other):
        return self.f < other.f

def astar(maze, start, end):
    # Initialize both open and closed lists
    open_list = []
    closed_list = set()

    start_node = Node(start)
    end_node = Node(end)
    heapq.heappush(open_list, start_node)

    while open_list:
        current_node = heapq.heappop(open_list)
        closed_list.add(current_node.position)

        if current_node.position == end_node.position:
            path = []
            while current_node:
                path.append(current_node.position)
                current_node = current_node.parent
            return path[::-1]  # Return reversed path

        neighbors = [(0, -1), (0, 1), (-1, 0), (1, 0)]  # Left, Right, Up, Down
        for direction in neighbors:
            neighbor_position = (current_node.position[0] + direction[0], current_node.position[1] + direction[1])

            if neighbor_position[0] < 0 or neighbor_position[0] >= len(maze) or neighbor_position[1] < 0 or neighbor_position[1] >= len(maze[0]):
                continue

            if maze[neighbor_position[0]][neighbor_position[1]] == 1:
                continue

            neighbor = Node(neighbor_position, current_node)

            if neighbor.position in closed_list:
                continue

            neighbor.g = current_node.g + 1
            neighbor.h = abs(neighbor.position[0] - end_node.position[0]) + abs(neighbor.position[1] - end_node.position[1])
            neighbor.f = neighbor.g + neighbor.h

            if any(open_node for open_node in open_list if neighbor.position == open_node.position and neighbor.g > open_node.g):
                continue

            heapq.heappush(open_list, neighbor)

    return None  # No path found

# Example usage
maze = [
    [0, 1, 0, 0, 0],
    [0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 0, 0, 0]
]

start = (0, 0)
end = (4, 4)

path = astar(maze, start, end)
if path:
    print("Path found:", path)
else:
    print("No path found")


Path found: [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4)]


ques3

In [ ]:
import heapq

# Uniform Cost Search (UCS)
def ucs(graph, start, goal):
    # Priority queue to store (cost, node, path)
    priority_queue = [(0, start, [])]
    visited = set()

    while priority_queue:
        (cost, node, path) = heapq.heappop(priority_queue)

        if node in visited:
            continue

        # Add current node to the visited set
        visited.add(node)
        path = path + [node]

        # Goal check
        if node == goal:
            return cost, path

        # Explore neighbors
        for neighbor, weight in graph.get(node, []):
            if neighbor not in visited:
                heapq.heappush(priority_queue, (cost + weight, neighbor, path))

    return float("inf"), []  # If no path is found

# Example usage
graph = {
    'A': [('B', 1), ('C', 4)],
    'B': [('D', 2), ('E', 5)],
    'C': [('E', 1)],
    'D': [('G', 3)],
    'E': [('G', 2)],
    'G': []
}

start = 'A'
goal = 'G'
cost, path = ucs(graph, start, goal)
print(f"Cost: {cost}, Path: {path}")


Cost: 6, Path: ['A', 'B', 'D', 'G']


q4

In [ ]:
# Pancake Problem - Sorting using flips
def flip(arr, i):
    """Flip function that reverses the array from 0 to i"""
    return arr[:i+1][::-1] + arr[i+1:]

def find_max_index(arr, n):
    """Find the index of the largest pancake in the array up to n"""
    return max(range(n), key=arr.__getitem__)

def pancake_sort(arr):
    """Sort the array using pancake flips"""
    n = len(arr)
    flips = []

    for i in range(n, 1, -1):
        max_index = find_max_index(arr, i)

        if max_index != i - 1:
            if max_index != 0:
                arr = flip(arr, max_index)
                flips.append(max_index + 1)

            arr = flip(arr, i - 1)
            flips.append(i)

    return arr, flips

# Example usage
pancakes = [3, 6, 1, 9, 2, 5]
sorted_pancakes, flips = pancake_sort(pancakes)

print(f"Sorted Pancakes: {sorted_pancakes}")
print(f"Flips: {flips}")


Sorted Pancakes: [1, 2, 3, 5, 6, 9]
Flips: [4, 6, 4, 5, 2, 4, 3]
